# Experiment 2 - Numerical Python (Numpy)

### Gaviana, John Phillip V.
### 2ECE-A

In [1]:
import numpy as np

## A. Reproducible Normalization Problem
## Requirement: Display X, X normalized, its mean, and its standard deviation.

In [2]:
np.random.seed(2112) #Creates a reproducible random 5x5 integer ndarray named X
X = np.random.randint(10, 101, size=(5, 5)) #Creates a reproducible random 5x5 integer ndarray named X

x_bar = X.mean() #Computes for the Mean
sigma = X.std() #Computes for the Standard Deviation
X_normalized = (X - x_bar)/sigma #Normalizes the Array

#Prints and Displays the Outputs of the Array
print("Array X:\n", X)
print("\nArray X_normalized:\n", X_normalized)
print("\nMean of X_normalized:", X_normalized.mean())
print("Standard Deviation of X_normalized:", X_normalized.std())

np.save("X_normalized.npy", X_normalized) #Saves the Normalized Array

Array X:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

Array X_normalized:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Mean of X_normalized: 0.0
Standard Deviation of X_normalized: 0.9999999999999999


## B. Cubes Divisible by 4 Problem 
## Requirement: Display the shape of C, the array div by 4, and the number of selected elements.

In [3]:
C = (np.arange(1, 101) ** 3).reshape(10,10) #Creates the first 100 positive integers, cubes every element, and reshapes the result into a 10x10 ndarray named C.

div_by_4 = C[C % 4 == 0] #Extract all elements from C that are divisible by 4 using Boolean indexing

#Prints and Displays the Outputs of the Array
print("Shape of C:", C.shape)
print("\nArray div_by_4:\n", div_by_4)
print("\nNumber of Selected Elements:", div_by_4.size)

np.save("div_by_4.npy", div_by_4) #Saves the Selected Array

Shape of C: (10, 10)

Array div_by_4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of Selected Elements: 50


## C. Above-Mean Squares Problem 
## Requirement: Display S, S mean, above mean, and the number of selected elements. 

In [4]:
S = (np.arange(1, 37) ** 2).reshape(6,6) #Creates a 6x6 ndarray named S that contains the squares of the first 36 positive integers in an increasing row-major order.

S_mean = S.mean() #Computes for the Mean of S

above_mean = S[S > S_mean] #Uses Boolean Filtering to extract only the elements strictly greater than S_mean

#Prints and Displays the Outputs of the Array
print("Array S: \n", S)
print("\nMean of S (S_mean):", S_mean)
print("\nArray above_mean:\n", above_mean)
print("\nNumber of Selected Elements:", above_mean.size)

np.save("above_mean.npy", above_mean) #Saves the Selected Array

Array S: 
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Mean of S (S_mean): 450.1666666666667

Array above_mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of Selected Elements: 15
